/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_decode_free: (a: number, b: number) => void;
export const decode_u32: (a: any) => [number, number, number];
export const decode_u64: (a: any) => [number, number, number];
export const decode_vec_string: (a: any) => [number, number, number];
export const decode_code_hash: (a: any) => [number, number, number];
export const decode_storage_keys: () => [number, number, number];
export const decode_epoch_duration: (a: any) => [number, number, number];
export const decode_gas_cost_table: (a: any) => [number, number, number];
export const decode_tx: (a: any) => [number, number, number];
export const decode_address: (a: any) => [number, number, number];
export const decode_addresses: (a: any) => [number, number, number];
export const decode_address_to_amount: (a: any) => [number, number, number];
export const decode_block: (a: number, b: number, c: number, d: number) => [number, number, number];
export const decode_pos_parameters: (a: any) => [number, number, number];
export const decode_pos_validator_metadata: (a: any) => [number, number, number];
export const decode_pos_commission_pair: (a: any) => [number, number, number];
export const decode_pos_validator_state: (a: any) => [number, number, number];
export const decode_pos_validator_set: (a: any) => [number, number, number];
export const decode_pgf_parameters: (a: any) => [number, number, number];
export const decode_gov_parameters: (a: any) => [number, number, number];
export const decode_gov_proposal: (a: any) => [number, number, number];
export const decode_gov_proposal_code_key: (a: bigint) => [number, number];
export const decode_balance_key: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const decode_gov_votes: (a: any) => [number, number, number];
export const decode_gov_result: (a: any) => [number, number, number];
export const decode_bonds_and_unbonds: (a: any) => [number, number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
